services:
  - type: web
    name: proyecto-romantico-completo
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
